import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import localFont from "next/font/local";
import toast, { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const PoppinsBold = localFont({
  src: "./fonts/Poppins-Bold.ttf",
  variable: "--font-poppins-bold",
  weight: "100 900",
});

const MontBold = localFont({
  src: "./fonts/Montserrat-Bold.ttf",
  variable: "--font-poppins-bold",
  weight: "100 900",
});

const MontMedium = localFont({
  src: "./fonts/Montserrat-Medium.ttf",
  variable: "--font-poppins-bold",
  weight: "100 900",
});

const SairaRegular = localFont({
  src: "./fonts/Saira-Regular.ttf",
  variable: "--font-saira-regular",
  weight: "100 900",
});

const SairaMedium = localFont({
  src: "./fonts/Saira-Medium.ttf",
  variable: "--font-saira-medium",
  weight: "100 900",
});

const SairaSemibold = localFont({
  src: "./fonts/Saira-SemiBold.ttf",
  variable: "--font-saira-semibold",
  weight: "100 900",
});

const SairaBold = localFont({
  src: "./fonts/Saira-Bold.ttf",
  variable: "--font-saira-bold",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Saylani Microfinance Webapp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <Header />
          <div>
            {children}
          </div>
          <Footer />
          <Toaster />
      </body>
    </html>
  );
}
